apiVersion: apps/v1
kind: Deployment
metadata:
  name: spde-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spde-frontend
  template:
    metadata:
      labels:
        app: spde-frontend
    spec:
      containers:
        - name: spde-frontend
          image: mordecai2508/spde-gr-frontend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5173
          env:
            - name: VITE_API_URL
              value: "http://spde-backend-service:3006"
---
apiVersion: v1
kind: Service
metadata:
  name: spde-frontend-service
spec:
  selector:
    app: spde-frontend
  ports:
    - protocol: TCP
      port: 5173
      targetPort: 5173
  type: LoadBalancer
